[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "tokencount"
publish = false
version = "0.0.0"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
maybe_xml = { path = "../../maybe_xml", features = ["internal_unstable"] }
